### ISSUE TITLE
"Non US" option for State can be chosen even if the "United States" is selected for Country on CustomerForm.html

### ISSUE THREAD

**Issue by nathan3o4** [ComputerMedicTeam/CAMT#10]
<img width="1442" alt="screen shot 2016-04-05 at 3 42 55 pm" src="https://cloud.githubusercontent.com/assets/6438337/14297563/1b6c67de-fb45-11e5-9cf5-31b6ac3ee010.png">

**Comment by acm482** [comment]
Assume to be usable for territories.
