### ISSUE TITLE
DATABASE – ID attributes for tables need to be auto incrementing

### ISSUE THREAD

**Issue by johnbuffington** [ComputerMedicTeam/CAMT#2]

**Comment by EvanFarry** [comment]
//Added Auto_Increment to CustomerID
//Changed Email_subscribed from 'text' to 'tinyint(1)'  

CREATE TABLE Customer_Suggestion
  (
  CustomerID int NOT NULL AUTO_INCREMENT,
  Name varchar(15) NOT NULL,
  Country varchar(20) NOT NULL,
  State varchar(20) NOT NULL,
  City varchar(20) NOT NULL,
  Street varChar(30) NOT NULL,
  ZIP int NOT NULL,
  Phone_Number int,
  Email_Address varchar(30),
  Age int, 
  Found_Business text,
  Notes text,
  Email_Subscribed tinyint(1),
  PRIMARY KEY (CustomerID)
  );

**Comment by acm482** [comment]
Fixed.
